USE ReservaHoteles



CREATE TABLE TBLAREA()
CREATE TABLE TBLCLIENT()
CREATE TABLE TBLEMPLOYEE()
CREATE TABLE TBLEVENT()
CREATE TABLE TBLEVENTATTENDANCE()
CREATE TABLE TBLFOOD()
CREATE TABLE TBLMEAL()
CREATE TABLE TBLMODULE()
CREATE TABLE TBLPACKAGE()
CREATE TABLE TBLPACKAGEINFO()
CREATE TABLE TBLPERMISION()
CREATE TABLE TBLPERSON()
CREATE TABLE TBLPURCHASE()
CREATE TABLE TBLPURCHASEINFO()
CREATE TABLE TBLRESERVATION()
CREATE TABLE TBLRESTAURANT()
CREATE TABLE TBLROLE()
CREATE TABLE TBLROOM()
CREATE TABLE TBLROOMITEMS()
CREATE TABLE TBLUSER()

INSERT INTO TBLAREA VALUES()
INSERT INTO TBLCLIENT VALUES()
INSERT INTO TBLEMPLOYEE VALUES()
INSERT INTO TBLEVENT VALUES()
INSERT INTO TBLEVENTATTENDANCE VALUES()
INSERT INTO TBLFOOD VALUES()
INSERT INTO TBLMEAL VALUES()
INSERT INTO TBLMODULE VALUES()
INSERT INTO TBLPACKAGE VALUES()
INSERT INTO TBLPACKAGEINFO VALUES()
INSERT INTO TBLPERMISION VALUES()
INSERT INTO TBLPERSON VALUES()
INSERT INTO TBLPURCHASE VALUES()
INSERT INTO TBLPURCHASEINFO VALUES()
INSERT INTO TBLRESERVATION VALUES()
INSERT INTO TBLRESTAURANT VALUES()
INSERT INTO TBLROLE VALUES()
INSERT INTO TBLROOM VALUES()
INSERT INTO TBLROOMITEMS VALUES()
INSERT INTO TBLUSER VALUES()


UPDATE TBLAREA SET 
UPDATE TBLCLIENT SET
UPDATE TBLEMPLOYEE SET
UPDATE TBLEVENT SET
UPDATE TBLEVENTATTENDANCE SET
UPDATE TBLFOOD SET
UPDATE TBLMEAL SET
UPDATE TBLMODULE SET
UPDATE TBLPACKAGE SET
UPDATE TBLPACKAGEINFO SET
UPDATE TBLPERMISION SET
UPDATE TBLPERSON SET
UPDATE TBLPURCHASE SET
UPDATE TBLPURCHASEINFO SET
UPDATE TBLRESERVATION SET
UPDATE TBLRESTAURANT SET
UPDATE TBLROLE SET
UPDATE TBLROOM SET
UPDATE TBLROOMITEMS SET
UPDATE TBLUSER SET

DELETE FROM TBLAREA WHERE
DELETE FROM TBLCLIENT WHERE
DELETE FROM TBLEMPLOYEE WHERE
DELETE FROM TBLEVENT WHERE
DELETE FROM TBLEVENTATTENDANCE WHERE
DELETE FROM TBLFOOD WHERE
DELETE FROM TBLMEAL WHERE
DELETE FROM TBLMODULE WHERE
DELETE FROM TBLPACKAGE WHERE
DELETE FROM TBLPACKAGEINFO WHERE
DELETE FROM TBLPERMISION WHERE
DELETE FROM TBLPERSON WHERE
DELETE FROM TBLPURCHASE WHERE
DELETE FROM TBLPURCHASEINFO WHERE
DELETE FROM TBLRESERVATION WHERE
DELETE FROM TBLRESTAURANT WHERE
DELETE FROM TBLROLE WHERE
DELETE FROM TBLROOM WHERE
DELETE FROM TBLROOMITEMS WHERE
DELETE FROM TBLUSER WHERE

go