USE ReservaHoteles

CREATE TABLE AREA(
	IDAREA	INT PRIMARY KEY,
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(100),
	LEVEL VARCHAR(100),
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	ACTIVE INT
)
CREATE TABLE CLIENT(
	IDCLIENT INT PRIMARY KEY,
	IDUSER INT,
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	ACTIVE INT
)
CREATE TABLE EMPLOYEE(
	IDEMPLOYEE INT PRIMARY KEY,
	IDROLE VARCHAR(100),
	IDUSER VARCHAR(100),
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	ACTIVE INT
)
CREATE TABLE EVENTS(
	IDEVENT INT PRIMARY KEY,
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(100),
	STARTDATE VARCHAR(100),
	ENDDATE VARCHAR(100),
	DURATION VARCHAR(100),
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	COST DECIMAL(10,2),
	IDAREA INT,
	ACTIVE INT
)
CREATE TABLE EVENTATTENDANCE(
	IDEVENTS INT,
	IDCLIENT INT
)
CREATE TABLE FOOD(
	IDFOOD INT PRIMARY KEY,
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(100),
	TYPE VARCHAR(100),
	COST DECIMAL(10,2),
	IDRESTAURANT INT,
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	ACTIVE INT
)
CREATE TABLE MEAL(
	IDMEAL INT,
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(100),
	COST DECIMAL(10,2),
	ACTIVE INT
)
CREATE TABLE MEALINFO(
	IDMEAL INT,
	IDFOOD INT
)

CREATE TABLE MODULE(
	IDMODULE INT PRIMARY KEY,
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(100),
	PATH VARCHAR(100),
	LEVEL VARCHAR(100),
	ORDER VARCHAR(100),
	IDFATHERMODULE VARCHAR(100),
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	ACTIVE INT
)

CREATE TABLE PACKAGE(
	IDPACKAGE INT PRIMARY KEY,
	NAME VARCHAR(100),
	COST DECIMAL(10,2),
	ACTIVE INT
)
CREATE TABLE PACKAGEINFO(
	IDPACKAGE INT,
	NAME VARCHAR(100),
	ACTIVE INT
)
CREATE TABLE PERMISION(
	IDPERMISSION INT PRIMARY KEY,
	IDMODULE INT,
	IDROLE INT,
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	ACTIVE INT
)
CREATE TABLE PERSON(
	IDPERSON INT PRIMARY KEY,
	FNAME VARCHAR(100),
	SNAME VARCHAR(100),
	ONAME VARCHAR(100),
	FSURNAME VARCHAR(100),
	SSURNAME VARCHAR(100),
	MSURNAME VARCHAR(100),
	DOB VARCHAR(100),
	GENDER VARCHAR(100),
	IDNO VARCHAR(100),
	PHONE VARCHAR(100),
	EMAIL VARCHAR(100),
	ETHNICITY VARCHAR(100),
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	ACTIVE INT
)

CREATE TABLE PURCHASE(
	IDPURCHASE INT PRIMARY KEY,
	DESCRIPTION VARCHAR(100),
	TRANSACTIONDATE VARCHAR(100),
	TOTAL DECIMAL(10,2),
	IDCLIENT INT
)

CREATE TABLE PURCHASEINFO(
	IDPURCHASE INT,
	COST DECIMAL(10,2),
	DISCOUNT DECIMAL(10,2),
	TOTAL DECIMAL(10,2),
	DESCRIPTION VARCHAR(100),
)

CREATE TABLE RESERVATION(
	IDRESRVATION VARCHAR(100) PRIMARY KEY,
	IDCLIENT INT,
	IDROOM INT,
	IDPACKAGE INT,
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	ACTIVE INT
)

CREATE TABLE RESTAURANT(
	IDRESTAURANT INT PRIMARY KEY,
	IDAREA INT,
	NAME VARCHAR(100),
	STARTTIME VARCHAR(100),
	ENDTIME VARCHAR(100),
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	ACTIVE INT
)

CREATE TABLE ROLES(
	IDROLE INT,
	NAME VARCHAR(100),
	DESCRIPTION VARCHAR(100),
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	ACTIVE INT
)

CREATE TABLE ROOM(
	IDROOM INT,
	NOSHOWERS INT,
	NOROOMS INT,
	DESCRIPTION VARCHAR(100),
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	IDAREA INT,
	ACTIVE INT
)

CREATE TABLE ROOMITEMS(
	IDROOM INT,
	NAME VARCHAR(100),
	ACTIVE INT
)

CREATE TABLE USERS(
	IDUSER INT,
	USERNAME VARCHAR(100),
	PASS VARCHAR(100),
	TYPE VARCHAR(100),
	DATECREA VARCHAR(100),
	DATEMOD VARCHAR(100),
	IDPERSON INT,
	ACTIVE INT
)

GO

SELECT 1 AS IDUSER,	'Javier' AS USERNAME,'sdadfsdf' as PASS, 'Admin' as TYPE, FORMAT(SYSDATETIME(),'YYYY-MM-DD HH:MM:ss') as DATECREA, FORMAT(SYSDATETIME(),'YYYY-MM-DD HH:MM:ss') as DATEMOD, 1 as IDPERSON, 1 as ACTIVE

SELECT 1 AS IDPERSON,'' AS FNAME,'' AS SNAME,'' AS ONAME,'' AS FSURNAME,'' AS SSURNAME,'' AS MSURNAME,'' AS DOB,'' AS GENDER,'' AS IDNO,'' AS PHONE,'' AS EMAIL,'' AS ETHNICITY,FORMAT(SYSDATETIME(),'YYYY-MM-DD HH:MM:ss') AS DATECREA,FORMAT(SYSDATETIME(),'YYYY-MM-DD HH:MM:ss') AS DATEMOD, 1 AS ACTIVE


INSERT INTO AREA VALUES()
INSERT INTO CLIENT VALUES()
INSERT INTO EMPLOYEE VALUES()
INSERT INTO EVENTS VALUES()
INSERT INTO EVENTATTENDANCE VALUES()
INSERT INTO FOOD VALUES()
INSERT INTO MEAL VALUES()
INSERT INTO MODULE VALUES()
INSERT INTO PACKAGE VALUES()
INSERT INTO PACKAGEINFO VALUES()
INSERT INTO PERMISION VALUES()
INSERT INTO PERSON VALUES()
INSERT INTO PURCHASE VALUES()
INSERT INTO PURCHASEINFO VALUES()
INSERT INTO RESERVATION VALUES()
INSERT INTO RESTAURANT VALUES()
INSERT INTO ROLES VALUES()
INSERT INTO ROOM VALUES()
INSERT INTO ROOMITEMS VALUES()
INSERT INTO USERS VALUES()


UPDATE AREA SET 
UPDATE CLIENT SET
UPDATE EMPLOYEE SET
UPDATE EVENTS SET
UPDATE EVENTATTENDANCE SET
UPDATE FOOD SET
UPDATE MEAL SET
UPDATE MODULE SET
UPDATE PACKAGE SET
UPDATE PACKAGEINFO SET
UPDATE PERMISION SET
UPDATE PERSON SET
UPDATE PURCHASE SET
UPDATE PURCHASEINFO SET
UPDATE RESERVATION SET
UPDATE RESTAURANT SET
UPDATE ROLES SET
UPDATE ROOM SET
UPDATE ROOMITEMS SET
UPDATE USERS SET

DELETE FROM AREA WHERE
DELETE FROM CLIENT WHERE
DELETE FROM EMPLOYEE WHERE
DELETE FROM EVENTS WHERE
DELETE FROM EVENTATTENDANCE WHERE
DELETE FROM FOOD WHERE
DELETE FROM MEAL WHERE
DELETE FROM MODULE WHERE
DELETE FROM PACKAGE WHERE
DELETE FROM PACKAGEINFO WHERE
DELETE FROM PERMISION WHERE
DELETE FROM PERSON WHERE
DELETE FROM PURCHASE WHERE
DELETE FROM PURCHASEINFO WHERE
DELETE FROM RESERVATION WHERE
DELETE FROM RESTAURANT WHERE
DELETE FROM ROLES WHERE
DELETE FROM ROOM WHERE
DELETE FROM ROOMITEMS WHERE
DELETE FROM USERS WHERE

go