//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Reservacion.WebReports {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="WebReports.ReportsWS")]
    public interface ReportsWS {
        
        // CODEGEN: Generating message contract since element name name from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ReportsWS/helloRequest", ReplyAction="http://webservices/ReportsWS/helloResponse")]
        Hotel_Reservacion.WebReports.helloResponse hello(Hotel_Reservacion.WebReports.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/ReportsWS/helloRequest", ReplyAction="http://webservices/ReportsWS/helloResponse")]
        System.Threading.Tasks.Task<Hotel_Reservacion.WebReports.helloResponse> helloAsync(Hotel_Reservacion.WebReports.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://webservices/", Order=0)]
        public Hotel_Reservacion.WebReports.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(Hotel_Reservacion.WebReports.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://webservices/", Order=0)]
        public Hotel_Reservacion.WebReports.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(Hotel_Reservacion.WebReports.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportsWSChannel : Hotel_Reservacion.WebReports.ReportsWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportsWSClient : System.ServiceModel.ClientBase<Hotel_Reservacion.WebReports.ReportsWS>, Hotel_Reservacion.WebReports.ReportsWS {
        
        public ReportsWSClient() {
        }
        
        public ReportsWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportsWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportsWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportsWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hotel_Reservacion.WebReports.helloResponse Hotel_Reservacion.WebReports.ReportsWS.hello(Hotel_Reservacion.WebReports.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            Hotel_Reservacion.WebReports.helloRequest inValue = new Hotel_Reservacion.WebReports.helloRequest();
            inValue.Body = new Hotel_Reservacion.WebReports.helloRequestBody();
            inValue.Body.name = name;
            Hotel_Reservacion.WebReports.helloResponse retVal = ((Hotel_Reservacion.WebReports.ReportsWS)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotel_Reservacion.WebReports.helloResponse> Hotel_Reservacion.WebReports.ReportsWS.helloAsync(Hotel_Reservacion.WebReports.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotel_Reservacion.WebReports.helloResponse> helloAsync(string name) {
            Hotel_Reservacion.WebReports.helloRequest inValue = new Hotel_Reservacion.WebReports.helloRequest();
            inValue.Body = new Hotel_Reservacion.WebReports.helloRequestBody();
            inValue.Body.name = name;
            return ((Hotel_Reservacion.WebReports.ReportsWS)(this)).helloAsync(inValue);
        }
    }
}
