//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Reservacion.WebOrders {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="WebOrders.OrdersWS")]
    public interface OrdersWS {
        
        // CODEGEN: Generating message contract since element name name from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/OrdersWS/helloRequest", ReplyAction="http://webservices/OrdersWS/helloResponse")]
        Hotel_Reservacion.WebOrders.helloResponse hello(Hotel_Reservacion.WebOrders.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/OrdersWS/helloRequest", ReplyAction="http://webservices/OrdersWS/helloResponse")]
        System.Threading.Tasks.Task<Hotel_Reservacion.WebOrders.helloResponse> helloAsync(Hotel_Reservacion.WebOrders.helloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://webservices/", Order=0)]
        public Hotel_Reservacion.WebOrders.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(Hotel_Reservacion.WebOrders.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://webservices/", Order=0)]
        public Hotel_Reservacion.WebOrders.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(Hotel_Reservacion.WebOrders.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdersWSChannel : Hotel_Reservacion.WebOrders.OrdersWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersWSClient : System.ServiceModel.ClientBase<Hotel_Reservacion.WebOrders.OrdersWS>, Hotel_Reservacion.WebOrders.OrdersWS {
        
        public OrdersWSClient() {
        }
        
        public OrdersWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hotel_Reservacion.WebOrders.helloResponse Hotel_Reservacion.WebOrders.OrdersWS.hello(Hotel_Reservacion.WebOrders.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            Hotel_Reservacion.WebOrders.helloRequest inValue = new Hotel_Reservacion.WebOrders.helloRequest();
            inValue.Body = new Hotel_Reservacion.WebOrders.helloRequestBody();
            inValue.Body.name = name;
            Hotel_Reservacion.WebOrders.helloResponse retVal = ((Hotel_Reservacion.WebOrders.OrdersWS)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotel_Reservacion.WebOrders.helloResponse> Hotel_Reservacion.WebOrders.OrdersWS.helloAsync(Hotel_Reservacion.WebOrders.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotel_Reservacion.WebOrders.helloResponse> helloAsync(string name) {
            Hotel_Reservacion.WebOrders.helloRequest inValue = new Hotel_Reservacion.WebOrders.helloRequest();
            inValue.Body = new Hotel_Reservacion.WebOrders.helloRequestBody();
            inValue.Body.name = name;
            return ((Hotel_Reservacion.WebOrders.OrdersWS)(this)).helloAsync(inValue);
        }
    }
}
